"""empty message

Revision ID: f1bdb27e55c5
Revises:
Create Date: 2025-04-29 10:50:57.440281

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

from app.infrastructure.adapters.alchemy.type_decorators import (
    PasswordTypeDecorator,
    StringUUID,
    UserNameTypeDecorator,
    UserSurnameTypeDecorator,
)

# revision identifiers, used by Alembic.
revision: str = "f1bdb27e55c5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", StringUUID(), nullable=False),
        sa.Column("surname", UserSurnameTypeDecorator(length=100), nullable=True),
        sa.Column("name", UserNameTypeDecorator(length=100), nullable=False),
        sa.Column("password", PasswordTypeDecorator(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
